### PR TITLE
Use generic haskell 7.8.4 travis config.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/semdoc/3)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[.travis.yml, line 10 at r1](https://reviewable.io:443/reviews/toktok/semdoc/3#-KW0AVuYdlN-QkcpaArp:-KW0AVuZrYw56u6zY6es:bkgelqe) ([raw file](https://github.com/toktok/semdoc/blob/cb934650850c79ca63aaeeefae5e175c42d86756/.travis.yml#L10)):_

> ``` YAML
> 
> env: CABALVER=1.18 GHCVER=7.8.4
> addons: {apt: {packages: [alex-3.1.7, happy-1.19.5, cabal-install-1.18, ghc-7.8.4], sources: [hvr-ghc]}}
> ```

who's alex?

---

_[semdoc.cabal, line 42 at r1](https://reviewable.io:443/reviews/toktok/semdoc/3#-KW0AOkdEKODv817GzHQ:-KW0AOkgXv55WR10A_zM:bj2fzoc) ([raw file](https://github.com/toktok/semdoc/blob/cb934650850c79ca63aaeeefae5e175c42d86756/semdoc.cabal#L42)):_

> ```
>     , mtl
>     , pandoc          >= 1.7
>     , pandoc-types    <= 1.16
> ```

why are you setting a max version?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/semdoc/3)_

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[.travis.yml, line 10 at r1](https://reviewable.io:443/reviews/toktok/semdoc/3#-KW0AVuYdlN-QkcpaArp:-KW0B9rEwNUE2AYXdq00:brcq8do) ([raw file](https://github.com/toktok/semdoc/blob/cb934650850c79ca63aaeeefae5e175c42d86756/.travis.yml#L10)):_
<details><summary>

<i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>



> who's alex?
> </details>
> https://www.haskell.org/alex/ a lexical analyser generator

---

_[semdoc.cabal, line 42 at r1](https://reviewable.io:443/reviews/toktok/semdoc/3#-KW0AOkdEKODv817GzHQ:-KW0BHaXj78LeSRcQt4l:bh5f3g) ([raw file](https://github.com/toktok/semdoc/blob/cb934650850c79ca63aaeeefae5e175c42d86756/semdoc.cabal#L42)):_
<details><summary>

<i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>



> why are you setting a max version?
> </details>
> It fails with 1.17.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/semdoc/3)_

**Comment by GrayHatter** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[semdoc.cabal, line 42 at r1](https://reviewable.io:443/reviews/toktok/semdoc/3#-KW0AOkdEKODv817GzHQ:-KW0BQyr7FPtoYlq5F67:b-36hyqm) ([raw file](https://github.com/toktok/semdoc/blob/cb934650850c79ca63aaeeefae5e175c42d86756/semdoc.cabal#L42)):_
<details><summary>

<i>Previously, iphydf wrote…</i></summary>



> It fails with 1.17.
> </details>
>  I guessed that,  I was thinking more: do you know why? Or Do you want to add a comment?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/semdoc/3)_

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/semdoc/3#-:-KW0CHCeIXVWmr2QQF_q:b-jbsf8z)_

**Comment by iphydf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

_[semdoc.cabal, line 42 at r1](https://reviewable.io:443/reviews/toktok/semdoc/3#-KW0AOkdEKODv817GzHQ:-KW0CO3Hh758vcOShZwy:b-896fix) ([raw file](https://github.com/toktok/semdoc/blob/cb934650850c79ca63aaeeefae5e175c42d86756/semdoc.cabal#L42)):_
<details><summary>

<i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>



>  I guessed that,  I was thinking more: do you know why? Or Do you want to add a comment?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/semdoc/3)_

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/semdoc/3)_

**Pull request merged**
